"""Bundle the stylesheets into one file: css/site.css (one request instead of 8-12).

    python3 tools/build-css.py

Edit the individual files in css/ as normal, then re-run this. The order below
matches the order pages loaded them before bundling, so the cascade is unchanged.
Every page links only /css/site.css.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ORDER = ["icons", "style", "base", "navbar", "buttons", "testimonial", "footer",
         "hero-option", "collections", "enquiry", "packages", "locations"]

out = ["/* GENERATED by tools/build-css.py from css/*.css — do not edit this file directly. */\n"]
for name in ORDER:
    css = open(os.path.join(ROOT, "css", name + ".css"), encoding="utf-8").read()
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)        # drop comments
    css = re.sub(r"[ \t]+\n", "\n", css)
    css = re.sub(r"\n{2,}", "\n", css).strip()
    assert css.count("{") == css.count("}"), name
    out.append(f"/* --- {name}.css --- */\n{css}\n")
bundle = "\n".join(out)
open(os.path.join(ROOT, "css", "site.css"), "w", encoding="utf-8").write(bundle)
print(f"css/site.css: {len(bundle):,} bytes from {len(ORDER)} files")
